---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.rune.io
  resources:
  - secretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rune.io
  resources:
  - secretstores/finalizers
  verbs:
  - update
- apiGroups:
  - core.rune.io
  resources:
  - secretstores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.rune.io
  resources:
  - shadowsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.rune.io
  resources:
  - shadowsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - core.rune.io
  resources:
  - shadowsecrets/status
  verbs:
  - get
  - patch
  - update
